name: Deploy Airflow to EC2

on:
  push:
    branches:
      - main
    paths:
      - "dags/**"
      - "config/**"
      - "docker-compose.yaml"
      - ".github/workflows/deploy.yml"

env:
  INSTANCE_ID: "i-0f886fb3f9553d527"
  AWS_REGION: "us-west-2"

permissions:
  contents: read
  id-token: write

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::673541324313:role/Airflow-CI-CD
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      # Step 3: Start the EC2 instance (if stopped)
      - name: Start EC2 instance
        run: |
          aws ec2 start-instances --instance-ids ${{ env.INSTANCE_ID }} --region ${{ env.AWS_REGION }}
          aws ec2 wait instance-running --instance-ids ${{ env.INSTANCE_ID }} --region ${{ env.AWS_REGION }}

      # Step 4: Deploy via Git Pull and Restart Airflow
      - name: Deploy and restart Airflow via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=InstanceIds,Values=${{ env.INSTANCE_ID }}" \
            --parameters 'commands=[
              "cd /home/ec2-user/airflow",
              "git pull origin main",
              "docker compose down",
              "docker compose up --build -d"
            ]'
